Python3testequipmentname (#198)
* Initial python3 with explicit paths

* Tests updated

diff --git a/checkall b/checkall
--- a/checkall
+++ b/checkall
@@ -14,18 +14,14 @@ if [ "$?" != "0" ]; then
     echo "!!!!!!!!!! Unit Tests Failed !!!!!!!!!!"
     exit 1
 fi
-#echo "Recipe test.."
-#./testrecipe > /dev/null
-#if [ "$?" != "0" ]; then
-#    echo "!!!!!!!!!! Recipe Tests Failed !!!!!!!!!!"
-#    exit 1
-#fi
-#echo "BeerSmith bsmx test.."
-#./testbsmx > /dev/null
-#if [ "$?" != "0" ]; then
-#    echo "!!!!!!!!!! BeerSmith Tests Failed !!!!!!!!!!"
-#    exit 1
-#fi
+
+echo "bsmx read of equipmentname test, lightweight initial test.."
+./testequipmentname > /dev/null 2>&1
+if [ "$?" != "0" ]; then
+    echo "!!!!!!!!!! bsmx read of equipmentname Tests Failed !!!!!!!!!!"
+    exit 1
+fi
+
 echo "json to stages test.."
 ./testjson2stages > /dev/null 2>&1
 if [ "$?" != "0" ]; then
