removed test of old runctrl.py

diff --git a/checkall b/checkall
--- a/checkall
+++ b/checkall
@@ -11,18 +11,18 @@ if [ "$?" != "0" ]; then
     echo "!!!!!!!!!! Selenium test failed !!!!!!!!!!"
     exit 1
 fi
-echo "Recipe test.."
-./testrecipe > /dev/null
-if [ "$?" != "0" ]; then
-    echo "!!!!!!!!!! Recipe Tests Failed !!!!!!!!!!"
-    exit 1
-fi
-echo "BeerSmith bsmx test.."
-./testbsmx > /dev/null
-if [ "$?" != "0" ]; then
-    echo "!!!!!!!!!! BeerSmith Tests Failed !!!!!!!!!!"
-    exit 1
-fi
+#echo "Recipe test.."
+#./testrecipe > /dev/null
+#if [ "$?" != "0" ]; then
+#    echo "!!!!!!!!!! Recipe Tests Failed !!!!!!!!!!"
+#    exit 1
+#fi
+#echo "BeerSmith bsmx test.."
+#./testbsmx > /dev/null
+#if [ "$?" != "0" ]; then
+#    echo "!!!!!!!!!! BeerSmith Tests Failed !!!!!!!!!!"
+#    exit 1
+#fi
 echo "json to stages test.."
 ./testjson2stages > /dev/null
 if [ "$?" != "0" ]; then
