Communicationtest (#60)
* Initial web socket running

* Updated readme

* add main

* Class initial

* server objectified

* Cleanup

* New command, terminate

* wip

* Working commands

* Shell wrapper for send and recieve running together

* Working long buffer

* Updated tests

diff --git a/checkall b/checkall
--- a/checkall
+++ b/checkall
@@ -41,6 +41,12 @@ if [ "$?" != "0" ]; then
     echo "!!!!!!!!!! Thread BeerSmith Tests Failed !!!!!!!!!!"
     exit 1
 fi
+echo "Testing communication specific code..."
+./testcomm > /dev/null
+if [ "$?" != "0" ]; then
+    echo "!!!!!!!!!! Communication specific code failed !!!!!!!!!!"
+    exit 1
+fi
 echo "Testing HW specific software..."
 ./testHWcode > /dev/null
 if [ "$?" != "0" ]; then
