packages and modules right, added runctrl.py

diff --git a/testme b/testme
--- a/testme
+++ b/testme
@@ -1,17 +1,10 @@
 #!/bin/bash
-
-pushd ctrl > /dev/null
-echo -n "=========================" 
-pwd | cut -d "/" -f ` pwd | sed 's/\//x /g' | wc -w`
 nosetests
-if [ "$?" != "0" ]; then popd; exit 1; fi
-popd > /dev/null
-
-pushd cgi-bin > /dev/null
-echo -n "=========================" 
-pwd | cut -d "/" -f ` pwd | sed 's/\//x /g' | wc -w`
-nosetests
-if [ "$?" != "0" ]; then popd; exit 1; fi
-popd > /dev/null
-
-echo "===========All Tests Passed================"
+if [ "$?" == "0" ] 
+then
+    echo "===========All Tests Passed================"
+    exit 0
+else
+    echo "!!!!!!!!!! Tests Failed !!!!!!!!!!"
+    exit 0
+fi
